name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Roda apenas quando houver push na branch main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Configurar Autenticação no Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Fazer Login no Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.ARTIFACT_REGISTRY }}

      - name: Construir e Enviar a Imagem Docker
        run: |
          docker build -t ${{ secrets.ARTIFACT_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/meu-repo/meu-app:latest .
          docker push ${{ secrets.ARTIFACT_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/meu-repo/meu-app:latest

      - name: Fazer Deploy no Cloud Run
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
            --image=${{ secrets.ARTIFACT_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/meu-repo/meu-app:latest \
            --region=${{ secrets.CLOUD_RUN_REGION }} \
            --platform=managed \
            --allow-unauthenticated
